# Copyright 2024-2025 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Generated by zig-ebuilder 0.3.0

EAPI=8

DESCRIPTION="Command-line fuzzy finder that prioritizes matches on filenames"
HOMEPAGE="https://github.com/natecraddock/zf"

declare -g -r -A ZBS_DEPENDENCIES=(
	[libxev-12207b7a5b538ffb7fb18f954ae17d2f8490b6e3778a9e30564ad82c58ee8da52361.tar.gz]='https://github.com/mitchellh/libxev/archive/f6a672a78436d8efee1aa847a43a900ad773618b.tar.gz'
	[vaxis-1220de23a3240e503397ea579de4fd85db422f537e10036ef74717c50164475813ce.tar.gz]='https://github.com/rockorager/libvaxis/archive/refs/tags/v0.5.1.tar.gz'
	[zg-122055beff332830a391e9895c044d33b15ea21063779557024b46169fb1984c6e40.tar.gz]='https://codeberg.org/atman/zg/archive/v0.13.2.tar.gz'
	[zig-aio-1220a55aedabdd10578d0c514719ea39ae1bc6d7ed990f508dc100db7f0ccf391437.tar.gz]='https://github.com/Cloudef/zig-aio/archive/b5a407344379508466c5dcbe4c74438a6166e2ca.tar.gz'
	[zigimg-1220dd654ef941fc76fd96f9ec6adadf83f69b9887a0d3f4ee5ac0a1a3e11be35cf5.tar.gz]='https://github.com/zigimg/zigimg/archive/3a667bdb3d7f0955a5a51c8468eac83210c1439e.tar.gz'
	[zigwin32-1220da4cab188b7b0e351de67626ca0dcadceddd16ca5997cfb578697f0525a59dac.tar.gz]='https://github.com/marlersoft/zigwin32/archive/4a78e716ae6496f52d9ddaf4fda2c4bb692631cd.tar.gz'
)

ZIG_SLOT="0.13"
inherit shell-completion zig

SRC_URI="
	https://github.com/natecraddock/zf/archive/refs/tags/${PV}.tar.gz -> ${P}.tar.gz
	${ZBS_DEPENDENCIES_SRC_URI}
"

# zf, libxev, zg, zig-aio, zigimg, zigwin32: MIT
# vaxis: Apache-2.0
LICENSE="MIT Apache-2.0"
SLOT="0"
KEYWORDS="~amd64"

# We are third-party repository
RESTRICT="mirror"

DOCS=( "README.md" "CHANGELOG.md" "doc/zf.md" "doc/lib.md" )

src_configure() {
	local my_zbs_args=(
		-Dpie=true
		-Dwith_tui=true
	)

	zig_src_configure
}

src_install() {
	zig_src_install
	doman doc/zf.1

	dobashcomp complete/zf
	dozshcomp complete/_zf
	dofishcomp complete/zf.fish
}
